### ISSUE TITLE
Array type is not sanitized when in nested type

### ISSUE THREAD

**Issue by Martin521** [nojaf/telplin#15]
I came across this while working on #14

https://nojaf.com/telplin/#data=N4KABGBECWC2AOAbAprZA7ALgQ09A9upAFxSz4AmArimACrKJLToA6b6KmYAbmALxgA2gB8ADCIC6AGjBj2kEAF8gA

Implementation
```
module Telplin

let v = [|0|], 0
```

Signature
```
module Telplin

val v: int[] * int
```

Problem description

Should be
```
module Telplin

val v: int array * int
```

The proposed signature has problems.
I would be willing to help fix this.

**Comment by Martin521** [comment]
I think I can apply the SynType processing that I used in #14 now in sanitizeType. Perhaps even define a function 

`applyRecursively (SynType -> SynType) -> SynType -> SynType` that I can use in both places.

**Comment by nojaf** [comment]
Hi @Martin521, good catch! Having such a function would make sense. Are you interested in submitting a PR for this one?

**Comment by Martin521** [comment]
Yes, I will
