### ISSUE TITLE
Equality constraint is missing

### ISSUE THREAD

**Issue by nojaf** [nojaf/telplin#19]
Issue created from [telplin-online](https://nojaf.com/telplin/#data=N4KABGBECWC2AOAbAprZA7ALgQ09A9upAFxSz4AmArimACrKJLToA6b6%2B8GYAygJ4BnTKgB0AYXyIUAYzyFBogOIZkAJ2gz2XHgOFiAMiwCO7dpn7cwLEWvTZEYJWuzwAFgB4A5ADlKyAD4wAF4wAEkAJWRsCgB5dER%2BABFNeXs1fm8-CmQAGjBffwBtAF0AswTkTDAYijCAMwBZaEFBFgBzLP8wAHc3HkKc0mRjKgdoCyCACk4cwVJB5DBBEYBKMCn2l3dSZ1dPRYD13e2D7MCQ9ggIWeRBK%2BuAHyDeEdFkAA8ZZHhqzdPRABpZBCMDPPhvTD4ACCahc-FWDwg4PqVHQYFgLTa6HaYAAtOV0ddiShqlDoRQKCEMViOmCXm9YK4Nqj0eiCWBgfwAGoOKjIAAK2Ggahm%2BSKj0eJVW63Br2MonJcOw-CRxLApLAH1IXN5iH5QpFXRy%2BUWpQCpWpsPholc3HQVP%2B%2B3pEIVSvh63JlLVxI%2Bojo%2BBScgI6X4UymrI2ur5SymH3yAH0Zfigh9VvkI2ioyC9fyNgn8gA3ZMc4vHIKRaJxBLJVIh7AZDwFsAJwnsAD0nbA4jU0RENTAvcL6hWYHw9TAmH6YC2%2B3YmqHI9j%2BA07RYDj2Oycp2NgWO2-2u6CwTVK%2Bga-siE3bjVXck0mQchq0jAyAo7TuarlbxkUlkf0jKZo31WNoAoeMwByeBBBLIIoMEF1rRVUQmXgFksyglNrHA-IoJlW9223fAqDQqCMAobAsAQ8dJ2nQRsDQSCfnIjAZGgO5J3wD8p3UL8GQVLZiPgAAhfhlgdAjuwUTA1CoJ9FzUFYqVndw%2BNdFDmUzdEpig-I3w-GCsN0193w478FVQsB6mEF15UVGFlQRNTexieJEiDTA1NqBpmlaOkzwvDcAS5QRIBAABfIA)

#### Implementation

```fsharp
module Telplin

open System.Collections.Generic
open System.Linq

type internal Graph<'Node> = IReadOnlyDictionary<'Node, 'Node[]>

let addIfMissing<'Node when 'Node: equality> (nodes: 'Node seq) (graph: Graph<'Node>) : Graph<'Node> =
    nodes
    |> Seq.except (graph.Keys |> Seq.toArray)
    |> fun missing ->
        let toAdd = missing |> Seq.map (fun n -> KeyValuePair(n, [||])) |> Seq.toArray
        let x: KeyValuePair<'Node, 'Node[]>[] = Array.append (graph |> Seq.toArray) toAdd
        x.ToDictionary((fun (KeyValue (x, _)) -> x), (fun (KeyValue (_, v)) -> v)) :> IReadOnlyDictionary<_, _>

/// Create a reverse of the graph
let reverse (originalGraph: Graph<'Node>) : Graph<'Node> =
    originalGraph
    // Collect all edges
    |> Seq.collect (fun (KeyValue (idx, deps)) -> deps |> Array.map (fun dep -> idx, dep))
    // Group dependants of the same dependencies together
    |> Seq.groupBy snd
    // Construct reversed graph
    |> Seq.map (fun (dep, edges) -> dep, edges |> Seq.map fst |> Seq.toArray)
    |> readOnlyDict
    |> addIfMissing originalGraph.Keys
```
#### Signature

```fsharp
module Telplin

open System.Collections.Generic
open System.Linq

type internal Graph<'Node> = IReadOnlyDictionary<'Node, 'Node[]>
val addIfMissing<'Node when 'Node: equality> : nodes: 'Node seq -> graph: Graph<'Node> -> Graph<'Node>
/// Create a reverse of the graph
val reverse: originalGraph: Graph<'Node> -> Graph<'Node>

```

#### Problem description

> (9, 34) (9,39)errorFS0340
The signature and implementation are not compatible because the declaration of the type parameter 'Node' requires a constraint of the form 'Node: equality

#### Extra information

- [X] The proposed signature has problems.
- [ ] I or my company would be willing to help fix this.

**Comment by Martin521** [comment]
This looks like something I could try to tackle. Not this week though.

**Comment by Martin521** [comment]
For now just a simplified test case:

```
module Telplin

let f<'T when 'T: equality> (x: 'T) = x
let g (x: 'T) : 'T = f x
```

**Comment by nojaf** [comment]
Wanna do some pair programming on this one sometime?

**Comment by Martin521** [comment]
Yes, that would be great. I will ping you on Slack when I am back from travel.
