### ISSUE TITLE
Flexible parameter generation issue

### ISSUE THREAD

**Issue by TheAngryByrd** [nojaf/telplin#47]
Issue created from [telplin-online](https://nojaf.com/telplin/#data=N4KABGBECWC2AOAbAprZA7ALgQ09A9upAFxTrZoDO82AxsmAGKUAq%2B%2BiA1tJgHQCiAJ0H5BACWzoAJomjoA5gB10ygNoAeAIIBXTPgDy8DAD4Austj4p2lGABKySjcwBhfmAC8yiBEwBPI3tHZwAhbWhEKWRBAAoASk9vH2S0WAAjaLA5WXQGAH1eB0xtQXQYgDdsRG1kUgByfE4E0gcnREx1Bs4AGjA66JFBY08wfU4wSurkZTUtXQMjdDMLKxsGVuc3fgAPTAxKAnRKRJV0ZP9AjfawiKjBMAB3HgALGbPknwB6b7B1J1hYNhBH5jEkPmBvp8wAA5ZDIKJSMB6MBVRD4B5gAAGADNRLxeHJMSjpFjcYJ8VJ8ETsdp0LQ8IQqjw-GCPpDfp9-oDgaD3uDUhl7tk5PleABlfAlegxSikADElGQAEd1HljM0wArlarhh4wJRlJAQABfIA)

#### Implementation

```fsharp
namespace FsToolkit.ErrorHandling

[<AutoOpen>]
module ResultCE =
    type ResultBuilder() =
        member inline _.Return(value: 'ok) : Result<'ok, 'error> = Ok value

[<AutoOpen>]
module ResultCEExtensions =

    type ResultBuilder with

        /// <summary>
        /// Needed to allow `for..in` and `for..do` functionality
        /// </summary>
        member inline _.Source(s: #seq<_>) : #seq<_> = s

```
#### Signature

```fsharp
namespace FsToolkit.ErrorHandling

[<AutoOpen>]
module ResultCE =
    type ResultBuilder =
        new: unit -> ResultBuilder
        member inline Return: value: 'ok -> Result<'ok, 'error>

[<AutoOpen>]
module ResultCEExtensions =
    type ResultBuilder with

        /// <summary>
        /// Needed to allow `for..in` and `for..do` functionality
        /// </summary>
        member inline Source: s: #seq<_> -> 'a when 'a :> seq<'b>

```

#### Problem description

```
(16, 24) (16,30)errorFS0034
Module 'FsToolkit.ErrorHandling.ResultCEExtensions' contains member ResultBuilder.Source<'a,'b when 'a :> seq<'b>> : s: 'a -> 'a when 'a :> seq<'b> but its signature specifies member ResultBuilder.Source<'a0,'a1,'a,'b when 'a0 :> seq<'a1> and 'a :> seq<'b>> : s: #seq<'a1> -> #seq<'b> The respective type parameter counts differ
```

#### Extra information

- [X] The proposed signature has problems.
- [x] I or my company would be willing to help fix this.

**Comment by nojaf** [comment]
Hi Jimmy, thanks for the issue report.
Everybody gets one: https://github.com/nojaf/telplin/pull/50

Cheers
