### ISSUE TITLE
Type inference of extension members, type inference of constraints, online tool limitations

### ISSUE THREAD

**Issue by Martin521** [nojaf/telplin#6]
Issue created from [telplin-online](https://nojaf.com/telplin/index.html#data=N4KABGBECWC2AOAbAprZA7ALgQ09A9upAFxTrZoDO82AxsmACrKWYA66Hs%2BAJgK4owAGWisAogA9MYALwcIEFNIBm%2BRDwDqAC2goAPAHJGAGjAGAyjkzIAfGFXrkAJzAAKaOmh5siS7mSkFlbIAJRuHvB8mIGMYIiimGFy6AqpccjSsFHYAEaCrP6yYB5e0D5%2B1vJpihlgWTh5DPGsRRFRVdUA7jqC6PjSzZgAdACSlGIImACeYDz4HdUKsLi0WvZqPM5gBdZxCUMAEsjYPGCdXloLi2AAPmAAcoQMALR2g2B6z2AA2gC6V4s7uZ8GhtsEDGBXgDrhAdgxPmD-AZoTD3gjBkNGNhdCi4RwuLwBAwRKwAEwAEVkCyUdWw8HsRRJw2W9NcTKGLPsIWptRZpIZMmE%2Bz5bnZIuU3JSChpXi2ykZ%2B1lLjZiusLglPOkSugAqFrCG2rcyj4KRcEkhdnZhtc8qcYQkktSNJZOvlgrFdJ1NrANktws9jultQcp3llAV%2BpDov2UYl201tPgADENgzw%2B7-cnUyr9SyU%2BoufHOFKalr0JsJMhTohSadktcreXkJXq7Xbn7c3SjSa3E5TE58J0wq89cMPBWq2AB5126OOV2bT3XLRTA6LVPTCuwA7JQnYB4AEIzN1zzk55mH49hX2ny-2BMeeLoBiUPiwOJtjP61%2BwI9zn8fjwD7oE%2BL5vn%2B8o1nW-7gTM55DD%2BEFhFB%2BLoN8egAIJRPgADy8AYDY-zoNw-CCAAsnSkjWOglAEDRVIlmA0z4WAFHwIYADSpgGAAamcWgYGYHGkLQII0E4oiEHY5yYJcxbXGgsA5FssBDBxyBTOmdSzmxQyYPgTKzh69LKKwKKKcpLiqTxPh8CwRTvjcdi6fphlOaeXaUOWqGQCAAC%2BQA)

#### Implementation

```fsharp
namespace Test

module ListExt =
    let foldWhile<'T, 'State> folder (initialState: 'State) (input: 'T list) =
        let mutable state = initialState
        let mutable list = input
        while not list.IsEmpty do
            match folder state list.Head with
            | None -> list <- []
            | Some state' ->
                state <- state'
                list <- list.Tail
        state

module List2D =
    let map f = List.map (List.map f)
    let map2 f = List.map2 (List.map2 f)
    let iter f = List.iter (List.iter f)
    let iteri f = List.iteri (fun r x -> List.iteri (f r) x)
    let mapi f = List.mapi (f >> List.mapi)
    let fold f s = List.fold (List.fold f) s
    let mapFold f s = List.mapFold (List.mapFold f) s

    let indexed l2d =
        List.indexed l2d |> List.map (fun (r, row) -> List.indexed row |> List.map (fun (c, x) -> r, c, x))

    let minBy f = List.map (List.minBy f) >> List.minBy f
    let inline sum l2d = List.sumBy List.sum l2d
    let inline sumBy f l2d = List.sumBy (List.sumBy f) l2d

[<AutoOpen>]
module MapExtensions =
    type Map<'K, 'V when 'K: comparison> with

        member m.Keys = m |> Map.toList |> List.map fst
        member m.Values = m |> Map.toList |> List.map snd


```
#### Signature

```fsharp
namespace Test

module ListExt =
    val foldWhile<'T, 'State> :
        folder: ('State -> 'T -> 'State option) -> initialState: 'State -> input: 'T list -> 'State

module List2D =
    val map: f: ('a -> 'b) -> ('a list list -> 'b list list)
    val map2: f: ('a -> 'b -> 'c) -> ('a list list -> 'b list list -> 'c list list)
    val iter: f: ('a -> unit) -> ('a list list -> unit)
    val iteri: f: (int -> int -> 'a -> unit) -> ('a list list -> unit)
    val mapi: f: (int -> int -> 'a -> 'b) -> ('a list list -> 'b list list)
    val fold: f: ('a -> 'b -> 'a) -> s: 'a -> ('b list list -> 'a)
    val mapFold: f: ('a -> 'b -> 'c * 'a) -> s: 'a -> ('b list list -> 'c list list * 'a)
    val indexed: l2d: 'a list list -> (int * int * 'a) list list
    val minBy: f: ('a -> 'b) -> ('a list list -> 'a)
    val inline sum: l2d: ^a list list -> ^a
    val inline sumBy: f: ('a -> ^b) -> l2d: 'a list list -> ^b

[<AutoOpen>]
module MapExtensions =
    type Map<'K, 'V when 'K: comparison> with

        member Keys: 'Key list
        member Values: 'Value list

```

#### Problem description

1. In module List2D, the type constraints for the minBy/sum/sumBy functions are not properly inferred.
2. In MapExtensions.Map, the member type names are not correct.
3. In the online tool error messages, the line numbers are not correct.
4. In the online tool, on a laptop screen, the error messages take so much space that only a single line of the signature is visible.

#### Extra information

- [X] The proposed signature has problems.
- [ ] I or my company would be willing to help fix this. (well, willing, but probably not able)

**Comment by nojaf** [comment]
Hello, thank you for trying out Telplin.
There are still some gaps indeed.
Are you interested in contributing?

**Comment by nojaf** [comment]
You could get your feet wet by trying to solve [the first problem](https://nojaf.com/telplin/#data=N4KABGBECWC2AOAbAprZA7ALgQ09A9upAFxSz4AmArimADLQDOmATACIA66XKmYs0dACEAnmABmYALz0mmAHSxs8MAAoGzRYNESAlGAB8B2ZoHCx4yCAC%2BQA).

Create a failing unit test in [BindingTests.fs](https://github.com/nojaf/telplin/blob/main/tests/Telplin.Core.Tests/BindingTests.fs).
Try and figure out what information is available in TypedTree:
https://github.com/nojaf/telplin/blob/266a64f654657ef16e28b630b62948296597aaa3/src/Telplin.TypedTree/TypedTree.fs#L79-L88

And process that accordingly in UntypedTree:

https://github.com/nojaf/telplin/blob/266a64f654657ef16e28b630b62948296597aaa3/src/Telplin.UntypedTree/UntypedTree.fs#L483-L534

I would start there for a first PR, keep is scoped to one single problem. You'll see how it goes. Don't hesitate to ask any questions.

**Comment by Martin521** [comment]
The necessary information (comparison constraint on 'b) is available in the typed tree, but not in the untyped tree.

I think the first step would be to extend `GenericConstraint` by `IsComparisonConstraint : bool` and set it in TypedTree around line 80. Next I would look for where the `GenericConstraint` is used and add the necessary code there.

 Does that make sense?

**Comment by nojaf** [comment]
Yes, that was more or less what I was expecting.

**Comment by Martin521** [comment]
Created PR #7

**Comment by Martin521** [comment]
Closing this as the problems are now covered by #7 , #8 , #9

**Comment by nojaf** [comment]
Thanks!
