### ISSUE TITLE
Extension methods get wrong type parameter names

### ISSUE THREAD

**Issue by Martin521** [nojaf/telplin#8]
Issue created from [telplin-online](https://nojaf.com/telplin/#data=N4KABGBECWC2AOAbAprZA7ALgQ09A9upAFxSz4AmArimAKIAemGAzgeiwDroQSYCe8ZGAAy0FpgA8AcjoA%2BMAHdomABbduvLWDSwARsgBOYNeIB0ADTABeE6vMAJZNgrdIIAL5A)

#### Implementation

```fsharp
module Extensions

type List<'E> with

    member this.X = this.Head

```
#### Signature

```fsharp
module Extensions

type List<'E> with

    member X: 'T

```

#### Problem description

It seems the type parameter names of the members are taken from the original class, not from the definition in the extension module.
This issue is a more concise example and description of the second item mentioned in issue #6.

~~A separate potential issue is the Telplin error message, which says `Module 'Extensions' contains member List.X: 'E but its signature specifies member List.X: obj The types differ` rather than reporting an internal error (invalid output). I am not sure if this is a bug or a feature.~~

#### Extra information

- [X] The proposed signature has problems.
- [X] I would be willing to help fix this.

**Comment by nojaf** [comment]
> A separate potential issue is the Telplin error message, which says 

I think the error message is fine in this case. It is the exact message you get from the F# compiler when type-checking both files in a project.

This problem is a tricky one, I encountered it at the time but did not have a good answer for it.

See
https://github.com/nojaf/telplin/blob/596bf48ea18d8ca10d30d75ab00b979d66287e2f/tests/Telplin.Core.Tests/TypeTests.fs#L416-L440

`IsExtensionMember` is `true` in the Symbol of the Typed tree.
If that is the case (and the generic parameters are present in the untyped tree), they should be translated somehow.

The `PostfixList` in the `SynTypeDefn` could be compared with the parent information found in the symbol.

One tricky aspect is that you can't simply replace any generic parameter.
([example](https://nojaf.com/telplin/#data=N4KABGBECWC2AOAbAprZA7ALgQ09A9upAFxSz4AmArimACrKJLToA6bWAnvMmADLQAzpgA8AcgCiAPjAB3aJgAW7dhAhpYAI2QAnMEqEA6ABriAbgBowYzjIAUZ4mLMBKMHc5PObu8icS3AF53F0gQAF8gA)).

I'm afraid I don't have much more pointers than that at the moment.

**Comment by Martin521** [comment]
> I think the error message is fine in this case.

Yes, I indeed get now `error FS0039: The type parameter 'T is not defined.`, which makes sense. But I am very sure that until yesterday I got `Module 'Extensions' contains member List.X: 'E but its signature specifies member List.X: obj The types differ`, as mentioned above. I am not sure what happened. Anyway, let's forget this for now.

And yes, I guess there are a lot of tricky issues in Telplin. Also my List2D.sumBy (member constraint) is trickier than List2D.minBy (comparison constraint). I feel I should read a bit more about the compiler first (which I wanted anyway). And solve some infrastructure problems that I have here. For now I would create another couple of concise issues so that I can close the big one.  If that is ok for you.

I would want to continue tackling the issues whenever I find time for it.

**Comment by nojaf** [comment]
> For now I would create another couple of concise issues so that I can close the big one. If that is ok for you.

Yup, sounds good.

**Comment by Martin521** [comment]
This one is actually not fixed (#10 fixes #9). Can we reopen it?

**Comment by nojaf** [comment]
Yup, my bad.

**Comment by Martin521** [comment]
We have the list of type parameters as declared in the type extension (i.e. in our implementation file) (called "declared typars" below) available in `mkSynTypeDefnSig` in the `PostfixList` in `componentInfo`.
We have the list of type parameters of the original type definition (called "original typars" below) available in the symbol that we get from the typed tree  (`resolver.findSymbol`,  `valSymbol.ApparentEnclosingEntity.GenericParameters`).

I see two options for the necessary translation.

1. Hand down the declared typars from `mkSynTypeDefnSig` to `mkSynMemberSig` to `mkSynValSig` to `mkSynTypeForSignature` to `mkSynTypForSignatureBasedOnTypedTree` and use them there (around line 396 of UntypedTree.fs) to map the original typars in `ts` to the declared typars.
2. Make the translation in `mkSynTypeDefnSig` (around line 644 of UntypedTree.fs). Get the original typars by getting the type symbol from the resolver. Map the `members` by recursively going through their SynTypes and replacing each occurence of an original typar in a `usedType` field by the corresponding declared typar.

Option 1 handles the types where they are processed also in other aspects and may therefore be more systematic.
Option 2 needs minimal change of existing code and may thus be less risky.

Which one makes more sense?

**Comment by nojaf** [comment]
Hello, sorry for the delay. I'm struggling a bit to give a definite answer to this one.

On one hand, if we can preserve anything from the untyped tree that would lead to the best UX.
But on a practical level, I think it will be a lot easier to deal with everything if we just give up on reusing any constraints from the untyped tree if the type has them. Resolve the type parameters from the typed tree, even though the untyped tree had the original typed value.

At the same time, resolving the type parameters and passing down a dictionary might also not be so complex.

Could I persuade you to pursue both options?

**Comment by Martin521** [comment]
Yes, sure. It may take some time though. I am quite busy with something else the next two weeks.

**Comment by Martin521** [comment]
I have a first working version for the above Option 1 on a branch in my fork. Still needs some polishing. But I will first now work on Option 2.

**Comment by nojaf** [comment]
Hi, sorry for the delay, I have been traveling.
Could you maybe just raise the two PRs? That way I can easily track everything down, and check out both solutions locally.

**Comment by Martin521** [comment]
done

**Comment by nojaf** [comment]
Thanks again for this PR, let me know if you would like a new release with this fix.

**Comment by Martin521** [comment]
Not for me, I have a working version now :-)
